# Generated by Django 3.1.6 on 2021-03-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=16)),
                ('contact_number', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
    ]
